### ISSUE TITLE
scp: ~/app_name/shared/config/application.yml: No such file or directory

### ISSUE THREAD

**Issue by aesnyder** [chouandy/capistrano-figaro-yml#5]
`scp: ~/app_name/shared/config/application.yml: No such file or directory`

I get that when running `bundle exec cap production setup`

I have verified that `~/app_name/shared/config` exists on the remote server.

**Comment by ecowork-andy** [comment]
The path of `application.yml` should be `~/shared/config` on the remote server.

**Comment by wolas** [comment]
```
ubuntu@ip:~/app_name/shared/config$ ls
application.yml  database.yml  newrelic.yml  secrets.yml  sidekiq.yml
```
Also, 

```
JakeMac:app_name wolas$ bundle exec cap demo setup
00:00 figaro_yml:setup
      01 mkdir -pv ~/app_name/shared/config
      01 ubuntu@ip 0.332s
(Backtrace restricted to imported tasks)
cap aborted!
scp: ~/app_name/shared/config/application.yml: No such file or directory
```

The file is there, but the error still is being thrown. 

Also tried:

`set :figaro_yml_remote_path, File.join(shared_path, "config", "application.yml")`

and the path was resolved very strange:

`scp: ~/app_name/shared/~/app_name/shared/config/application.yml: No such file or directory`

any thoughts?
